# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nahuel Garbezza
author: "Nahuel"
email: n.garbezza@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Desarrollador de software y Profesor de Programación Orientada a Objetos
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: ngarbezza
github_username: ngarbezza
instagram_username: ngarbezza
linkedin_username: nahuelgarbezza

google_analytics: UA-24086937-7

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

permalink: /:title

collections:
  posts:
    output: true
    permalink: /blog/:title
  drafts:
    output: true
    permalink: /drafts/:title

header_pages:
  - blog.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - .idea/
